[tool]
id = "nl.treinwijzer.lightphone"
label = "Treinwijzer"
versionCode = 2
versionName = "1.0.1"
permissions = ["android.permission.INTERNET", "android.permission.ACCESS_NETWORK_STATE", "android.permission.ACCESS_FINE_LOCATION"]
capabilities = []
orientation = "portrait"
serverPackage = "com.lightos"
