package nl.treinwijzer.lightphone

class Copy(private val language: Language) {
    private fun value(en: String, nl: String) = if (language == Language.ENGLISH) en else nl

    val app = "Treinwijzer"
    val privacy get() = value("Privacy", "Privacy")
    val continueLabel get() = value("Continue", "Doorgaan")
    val privacyNotice get() = value(
        "Your station searches and journey requests go through Treinwijzer on Cloudflare to NS. Tracking stores your chosen journey until 30 minutes after arrival; unread alerts are kept for 24 hours. An anonymous installation key expires after 90 days without use. Favourites and nearby-station coordinates stay on your phone. We do not use advertising or analytics.",
        "Je stationszoekopdrachten en reisaanvragen gaan via Treinwijzer op Cloudflare naar NS. Bij het volgen wordt je gekozen reis tot 30 minuten na aankomst bewaard; ongelezen meldingen blijven 24 uur bewaard. Een anonieme installatiesleutel verloopt na 90 dagen zonder gebruik. Favorieten en coördinaten voor stations in de buurt blijven op je telefoon. We gebruiken geen advertenties of analytics.",
    )
    val loading get() = value("Loading…", "Laden…")
    val networkError get() = value("Could not reach Treinwijzer. Check your connection and configuration.", "Treinwijzer is niet bereikbaar. Controleer je verbinding en configuratie.")
    val searchStation get() = value("Search station", "Station zoeken")
    val chooseStation get() = value("Choose station", "Kies station")
    val chooseLetter get() = value("Choose a letter", "Kies een letter")
    val stationIndex get() = value("Stations A–Z", "Stations A–Z")
    val noResults get() = value("No stations found.", "Geen stations gevonden.")
    val departures get() = value("Departures", "Vertrektijden")
    val departureDetails get() = value("Departure details", "Vertrekdetails")
    val disruptions get() = value("Disruptions", "Storingen")
    val currentDisruptions get() = value("Current disruptions", "Actuele storingen")
    val disruption get() = value("Disruption", "Storing")
    val plannedMaintenance get() = value("Planned maintenance", "Geplande werkzaamheden")
    val planned get() = value("Planned", "Gepland")
    val planner get() = value("Plan journey", "Reis plannen")
    val journeyDetails get() = value("Journey details", "Reisdetails")
    val journeyTimeline get() = value("Journey timeline", "Reisverloop")
    val favourites get() = value("Favourites", "Favorieten")
    val manageFavourites get() = value("Manage favourites", "Favorieten beheren")
    val settings get() = value("Settings", "Instellingen")
    val nearest get() = value("Nearest stations", "Stations in de buurt")
    val nearestShort get() = value("Nearest", "Dichtstbij")
    val nearestUnavailable get() = value(
        "Could not get a recent location. Try again outdoors, or search for a station.",
        "Geen recente locatie gevonden. Probeer het buiten opnieuw of zoek een station.",
    )
    val locationPermission get() = value("Allow location access to find nearby stations. Your location stays on your phone.", "Sta locatietoegang toe om stations in de buurt te vinden. Je locatie blijft op je telefoon.")
    val allowLocation get() = value("Allow location", "Locatie toestaan")
    val activeJourney get() = value("Active journey", "Actieve reis")
    val liveJourney get() = value("Live journey", "Live reis")
    val origin get() = value("From", "Van")
    val destination get() = value("To", "Naar")
    val via get() = value("Via (optional)", "Via (optioneel)")
    val leaveNow get() = value("Leave Now", "Vertrek nu")
    val departBy get() = value("Depart By", "Vertrek om")
    val arriveAt get() = value("Arrive At", "Aankomst om")
    val now get() = value("Now", "Nu")
    val options get() = value("Options", "Opties")
    val day get() = value("Day", "Dag")
    val time get() = value("Time", "Tijd")
    val today get() = value("Today", "Vandaag")
    val tomorrow get() = value("Tomorrow", "Morgen")
    val hour get() = value("Hour", "Uur")
    val minute get() = value("Minute", "Minuut")
    val planBy get() = value("Plan by", "Plan op")
    val useOptions get() = value("Use options", "Gebruik opties")
    val plan get() = value("Plan", "Plan")
    val swap get() = value("Swap", "Wissel")
    val removeVia get() = value("Remove via", "Verwijder via")
    val refresh get() = value("Refresh", "Vernieuwen")
    val recover get() = value("Alternatives", "Alternatieven")
    val stop get() = value("Stop", "Stop")
    val track get() = value("Track journey", "Reis volgen")
    val stopTracking get() = value("Stop tracking", "Stop volgen")
    val recovery get() = value("Recovery journeys", "Alternatieve reizen")
    val towards get() = value("Towards", "Richting")
    val fares get() = value("Fares", "Prijzen")
    val secondClass get() = value("Second class", "Tweede klas")
    val firstClass get() = value("First class", "Eerste klas")
    val supplement get() = value("Supplement", "Toeslag")
    val openActiveJourney get() = value("View live journey", "Bekijk live reis")
    val noJourneys get() = value("No journeys found.", "Geen reizen gevonden.")
    val noDepartures get() = value("No departures found.", "Geen vertrektijden gevonden.")
    val noDisruptions get() = value("No disruptions or planned maintenance.", "Geen storingen of geplande werkzaamheden.")
    val routeStops get() = value("Route stops", "Tussenstops")
    val information get() = value("Information", "Informatie")
    val direct get() = value("Direct", "Rechtstreeks")
    val addFavourite get() = value("Add favourite", "Favoriet toevoegen")
    val removeFavourite get() = value("Remove favourite", "Favoriet verwijderen")
    val saveRoute get() = value("Save route", "Route bewaren")
    val recents get() = value("Recents", "Recent")
    val favouriteStations get() = value("Favourite stations", "Favoriete stations")
    val noFavouriteStations get() = value("No favourite stations yet.", "Nog geen favoriete stations.")
    val favouriteRoutes get() = value("Favourite routes", "Favoriete routes")
    val noFavouriteRoutes get() = value("No favourite routes yet.", "Nog geen favoriete routes.")
    val useRoute get() = value("Use route", "Gebruik route")
    val travel get() = value("Travel", "Reizen")
    val route get() = value("Route", "Route")
    val more get() = value("More", "Meer")
    val alerts get() = value("Journey alerts", "Reismeldingen")
    val notifications get() = value("Notifications", "Meldingen")
    val guidance get() = value("Transfer guidance", "Overstapbegeleiding")
    val english get() = "English"
    val dutch get() = "Nederlands"
    val enabled get() = value("On", "Aan")
    val disabled get() = value("Off", "Uit")
    val unavailable get() = value("Unavailable", "Niet beschikbaar")
    val back get() = value("Back", "Terug")
    val close get() = value("Close", "Sluiten")
    val retry get() = value("Retry", "Opnieuw")
    val platform get() = value("Platform", "Spoor")
    val cancelled get() = value("Cancelled", "Opgeheven")
    val journeyChanged get() = value("Journey changed", "Reis gewijzigd")
    val platformChanged get() = value("Platform changed", "Spoor gewijzigd")
    val transfer get() = value("transfer", "overstap")
    val transfers get() = value("transfers", "overstappen")
    val minutes get() = value("min", "min")
    val price get() = value("Price", "Prijs")
    val configured get() = value("Connected", "Verbonden")
    val connection get() = value("Connection", "Verbinding")
    val notConfigured get() = value("Could not connect to Treinwijzer.", "Geen verbinding met Treinwijzer.")
    val notificationsLimited get() = value(
        "Journey updates and alerts appear while this tool is open. Unread alerts are kept for 24 hours and shown when you reopen it. There are no background notifications.",
        "Reisupdates en meldingen verschijnen als deze tool open is. Ongelezen meldingen blijven 24 uur bewaard en verschijnen bij de volgende start. Er zijn geen achtergrondmeldingen.",
    )
}
