[tool]
id = "com.thelightphone.uidemo"
label = "Light UI Demo"
versionCode = 1
versionName = "1.0.0"
permissions = ["android.permission.CAMERA", "android.permission.ACCESS_FINE_LOCATION"]
# for the LightOS emulator, use the line below and build with -DlightSdk.allowAltServerPackage=true
# serverPackage = "com.thelightphone.sdk.emulator"
serverPackage = "com.lightos"